### ISSUE TITLE
Compute Shader Run On Android Phone

### ISSUE THREAD

**Issue by Kaorixsol** [cinight/MinimalCompute#2]
Hello，I can`t use ComputeShader on Android. My Android is HUA WEI P30.

Android Build Setting in Unity:

![image](https://user-images.githubusercontent.com/20392465/120176126-82e67d80-c239-11eb-9125-7fb4a43e37e2.png)

Please Help me, Thanks!

**Comment by kilo45** [comment]
As far as I am aware Compute shaders dont work on phones
